#!/usr/bin/bash
readonly ID_PREVIEW="preview"

#AUTO_REMOVE="yes"

if [ -e "$FIFO_UEBERZUG" ]; then
    if [[ "$1" == "draw" ]]; then
        declare -p -A cmd=([action]=add [identifier]="$ID_PREVIEW"
                           [x]="$2" [y]="$3" [width]="$4" [height]="$5" \
                           [path]="${PWD}/$6") \
            > "$FIFO_UEBERZUG"

    elif [[ "$1" == "videopreview" ]]; then
        echo -e "Loading preview..\nFile: $6"
        ffmpegthumbnailer -i "${PWD}/$6" -o "/tmp/$6.png" -s 0 -q 10
        declare -p -A cmd=([action]=add [identifier]="$ID_PREVIEW"
                           [x]="$2" [y]="$3" [width]="$4" [height]="$5" \
                           [path]="/tmp/$6.png") \
            > "$FIFO_UEBERZUG"

    elif [[ "$1" == "gifpreview" ]]; then
        echo -e "Loading preview..\nFile: $6"
        [[ ! -d "/tmp/$6" ]] && mkdir -p "/tmp/$6" && convert -coalesce "${PWD}/$6" "/tmp/$6/$6.png"
        for frame in $(ls -1 /tmp/$6/$6*.png | sort -V); do
           declare -p -A cmd=([action]=add [identifier]="$ID_PREVIEW"
                           [x]="$2" [y]="$3" [width]="$4" [height]="$5" \
                           [path]="$frame") \
            > "$FIFO_UEBERZUG"
            sleep .07
            rm -f $frame
        done

    elif [[ "$1" == "pdfpreview" ]]; then
        echo -e "Loading preview..\nFile: $6"
        [[ ! -f "/tmp/$6.png" ]] && pdftoppm -png -singlefile "$6" "/tmp/$6"
        declare -p -A cmd=([action]=add [identifier]="$ID_PREVIEW"
                           [x]="$2" [y]="$3" [width]="$4" [height]="$5" \
                           [path]="/tmp/$6.png") \
            > "$FIFO_UEBERZUG"

    elif [[ "$1" == "clear" ]]; then
        declare -p -A cmd=([action]=remove [identifier]="$ID_PREVIEW") \
            > "$FIFO_UEBERZUG"
        [[ -z $AUTO_REMOVE ]] && [[ -f "/tmp/$6.png" ]] && rm -f "/tmp/$6.png"
    fi
fi

